# Generated by Django 6.0.3 on 2026-03-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='product_name',
        ),
    ]
