# Generated by Django 6.0.3 on 2026-03-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_products_name_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
