# Generated by Django 6.0.3 on 2026-03-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_created_at_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="slug",
            new_name="category_slug",
        ),
    ]
