# Generated by Django 6.0.3 on 2026-03-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_rename_slug_category_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_slug",
            new_name="slug",
        ),
    ]
