# Generated by Django 6.0.3 on 2026-03-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_rename_category_slug_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
    ]
