# Generated by Django 6.0.3 on 2026-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
